# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             127.0.0.1
port:             9001
url:              http://sui.taobao.org
encoding:         UTF-8

# Custom vars
current_version:  3.3.1
repo:             http://gitlab.alibaba-inc.com/sui/sui3
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.3.1.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.3.1.tar.gz

blog:             http://sui.taobao.org
expo:             http://sui.taobao.org

cdn:
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css
  css_theme:      https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js
